version: 0.0
os: linux
files:
  - source: build/libs/
    destination: /opt/ns3/dist/
  - source: deploy/ns3.service
    destination: /etc/systemd/system/
  - source: deploy/ns3-nginx.conf
    destination: /etc/nginx/conf.d/
hooks:
  BeforeInstall:
    - location: deploy/stop.sh
      runas: root
  AfterInstall:
    - location: deploy/install.sh
      runas: root
