version: 0.2

phases:
  build:
    commands:
      - gradle build jar
artifacts:
  files:
    - 'build/libs/*.jar'
    - 'deploy/*'
    - 'appspec.yml'
name: ns3-$(date +%Y-%m-%d).zip
discard-paths: no